model:
    _import_: models.vqtts.vqtts.VQTTS

    n_speakers: 1
    gin_channels: 0

    encoder:
        n_vocab: 148
        out_channels: &emb_width 128
        hidden_channels: 192
        filter_channels: 768
        filter_channels_dp: 256
        kernel_size: 3
        p_dropout: 0.1
        n_layers: 6
        n_heads: 2
        window_size: 4
        prenet: true
        mean_only: true

    levels: 3
    downs_t: [3, 3, 2]
    strides_t: [2, 2, 2]
    emb_width: *emb_width
    l_bins: 512
    mu: 0.99
    multipliers: [2, 1, 1]
    width: 64
    depth: 3
    m_conv: 1.0
    revival_threshold: 1.0
    use_bottleneck: true
    dilation_growth_rate: 3
    dilation_cycle: null
    kernel_size_growth_rate: 2
    kernel_size_cycle: null
    reverse_decoder_dilation: true
    zero_out: true

    block_type: gated_hifi

    ddi: false

    loss:
        commit: 0.05
        multispectral: 1.0
        align: 0.1

        l1: 0.0
        l2: 1.0
        linf: 0.02
        linf_topk: 2048

        n_ffts: [2048, 1024, 512]
        hop_lengths: [240, 120, 50]
        win_lengths: [1200, 600, 240]
        window: hann
        log: false

optimizer:
    name: adam
    lr: 0.0001
    betas: [0.9, 0.98]
    weight_decay: 0
    eps: 1e-9

scheduler: null
