dataset:
    _import_: datasets.ljspeech.LJSpeech

    dataset_path: ./data/LJSpeech-1.1
    cmudict_path: ./data/cmudict.dict

    sample_rate: 22050
    n_fft: 1024
    hop_length: 256
    win_length: 1024
    n_mels: 80
    intersperse_blanks: true
    segment_length: -1

    use_token: true
    use_spect: true
    use_audio: true
