# This workflow will install Python dependencies, lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linter and Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install toml==0.10.2 yapf==0.31.0 isort==5.9.3 pylint==2.11.0
    - name: Lint with yapf (version 0.31.0)
      run: |
        pylint *
        yapf --recursive --verbose --diff .
        isort . -c
